name: PHPUnit Tests

on:
  push:
    branches: [ trunk, develop ]
  pull_request:
    branches: [ trunk, develop ]

jobs:
  phpunit:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: wordpress_test
          MYSQL_USER: wp_test
          MYSQL_PASSWORD: password
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping --silent"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 3

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          tools: composer

      - name: Install MySQL Client
        run: sudo apt-get update && sudo apt-get install -y mysql-client

      - name: Install dependencies
        run: composer install

      - name: Download WordPress
        run: |
          curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
          chmod +x wp-cli.phar
          sudo mv wp-cli.phar /usr/local/bin/wp
          wp core download --path=/tmp/wordpress --allow-root

      - name: Setup WordPress configuration
        run: |
          wp config create --path=/tmp/wordpress --dbname=wordpress_test --dbuser=wp_test --dbpass=password --dbhost=127.0.0.1 --skip-check --allow-root

      - name: Install WordPress
        run: wp core install --path=/tmp/wordpress --url=http://localhost --title="Test" --admin_user=admin --admin_password=admin --admin_email=admin@example.com --allow-root

      - name: Install WordPress Test Suite
        env:
          DELETE_EXISTING_DB: "y"
        run: |
          bash bin/install-wp-tests.sh wordpress_test wp_test password 127.0.0.1 latest --allow-root

      - name: Run PHPUnit
        run: vendor/bin/phpunit
